### ISSUE TITLE
Update to 1.20.4

### ISSUE THREAD

**Issue by derpfriend** [luisch444/Hosting-luisch-Carpet#2]
Sorry, I don't know how else to request for a 1.20.4 update, thank you!

**Comment by luisch444** [comment]
Not worries, you can contact me using discord but this way is Okey.
The update its done, you may use 1.20.X version. I have not tested in all version but it should work. Feel free to reopen or comment in this issue if you need anything. 

Changes to be implemented into main in #3

**Comment by derpfriend** [comment]
thank you so much!
